model:
  speech_enhancement:
    config_path: /root/sogang_asr/enh_model_sc/exp/enh_train_enh_conv_tasnet_raw/config.yaml
    model_path:  /root/sogang_asr/enh_model_sc/exp/enh_train_enh_conv_tasnet_raw/5epoch.pth
